### PR TITLE
Responsive post images and OpenGraph implementation

### PR DESCRIPTION
**Pull request by anhchungite**

### CODE REVIEW

**Comment by anhchungite** [comment]
This is image display in my post.
screenshot 12

And sorry, I'll re-check indentions.

**Comment by anhchungite** [comment]
I want create new pull request separately for "Optimize title, description content and add open graph meta data" (26f755b) but I do not understand what is going .

**Comment by Lednerb** [comment]
Thank you for your contribution! :+1:

**Comment by rudedogg** [comment]
Just a heads up I don't think the scss changes are "compiled" in the latest release, I had to run `yarn run production` to get the responsive image change in this PR.

**Pull request merged**
