### PR TITLE
Add bilibili video support

### PR DESCRIPTION
**Pull request by hexsix**
Just another video site: https://bilibili.com 🙂

### CODE REVIEW

**Comment by igor-baiborodine** [comment]
@hexsix, your PR is being reviewed.

**Comment by igor-baiborodine** [comment]
The following changes are requested:
1. Add a link to the Bilibili site in the following sentence in `README.md`:
image.

2. Add the `bilibili` front matter variable to the [video archetype template](https://github.com/Lednerb/bilberry-hugo-theme/blob/master/archetypes/video.md).

Other than that, your PR was successfully tested with the Bilberry Sandbox:

https://deploy-preview-9--bilberry-sandbox.netlify.app/tags/bilibili/

**Review by igor-baiborodine — CHANGES_REQUESTED** [review]
Please see my comment in the Conversation section.

**Comment by hexsix** [comment]
@igor-baiborodine I've done that, with an unclosed angle brackets of `prezi-video-id` in README. 😜

**Review by igor-baiborodine — APPROVED** [review]

**Comment by igor-baiborodine** [comment]
@hexsix, thanks for your contribution!

**Pull request merged**
