### PR TITLE
Update master / Implement features from #234 and #239

### PR DESCRIPTION
**Pull request by Lednerb**

### CODE REVIEW

**Comment by nidomiro** [comment]
@Lednerb is it intentional that code blocks are the same color as the background if JS is disabled?

grafik

**Comment by Lednerb** [comment]
> @Lednerb is it intentional that code blocks are the same color as the background if JS is disabled?

Maybe there is a caching issue on your site or something else goes wrong.
If JS is disabled it should be rendered with a darker theme than the JS-one:

grafik

**Comment by nidomiro** [comment]
Interesting...
I checked out your master state (commit 89fb5eb)

Maybe the html-structure is different with asciidoc:

grafik

**Comment by Lednerb** [comment]
The following `html` block will be rendered by default:

grafik

grafik

```html
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-html" data-lang="html">&lt;<span style="color:#f92672">html</span>&gt;
    &lt;<span style="color:#f92672">head</span>&gt;
        &lt;<span style="color:#f92672">title</span>&gt;Hallo Welt&lt;/<span style="color:#f92672">title</span>&gt;
    &lt;/<span style="color:#f92672">head</span>&gt;
    &lt;<span style="color:#f92672">body</span>&gt;
        &lt;<span style="color:#f92672">h1</span>&gt;Hey!&lt;/<span style="color:#f92672">h1</span>&gt;
    &lt;/<span style="color:#f92672">body</span>&gt;
&lt;/<span style="color:#f92672">html</span>&gt;
</code></pre></div>
```

So the styling comes from `hugo` directly and the default theme is `monokai` IIRC

**Comment by Lednerb** [comment]
Is there a special use-case for using asciidoc?

**Comment by nidomiro** [comment]
The reason I prefer asciidoc over markdown is that asciidoc supports more features(https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/).
Now that I know, hugo handles the styling here, I can enable asciidoc to do the same by itself.

**Comment by Lednerb** [comment]
If you like, you can submit a PR for a asciidoc-related documentation covering how to use this theme with asciidoc.

This should be done in a separate document and not within the `README.md` directly.

**Comment by nidomiro** [comment]
I'm currently working on a style addiction for Asciidoc at https://github.com/nidomiro/bilberry-hugo-theme/tree/feature/asciidoc_fixes
I will send a PR if it's ready ;)

**Pull request merged**
