### PR TITLE
[WIP] Feature multi lang support #24

### PR DESCRIPTION
**Pull request by Lednerb**

### CODE REVIEW

**Comment by chibikun** [comment]
I am interested in providing the japanese version of the i18n because I would like to build a multilingual site based on the theme. When do you think the multilanguage feature would be ready to be used?

Thanks for the great theme!
David

**Comment by Lednerb** [comment]
Hey @chibikun 
Sorry for the late response...

This week I will work on this and release version 2.0.

I'm looking forward to having support for the Japanese language :+1:

**Comment by chibikun** [comment]
Hi Lednerb, That sounds perfect. Thanks a lot for the great work!.I will do the translation today or tomorrow. Best, David本当かよ。-------- Originalnachricht --------Betreff: Re: [Lednerb/bilberry-hugo-theme] [WIP] Feature multi lang support #24 -- Version 2.0.0 (#48)Von: Sascha Brendel An: Lednerb/bilberry-hugo-theme Cc: chibikun ,Mention Hey @chibikun
Sorry for the late response...
This week I will work on this and release version 2.0.
I'm looking forward to having support for the Japanese language 👍

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Lednerb/bilberry-hugo-theme","title":"Lednerb/bilberry-hugo-theme","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Lednerb/bilberry-hugo-theme"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Lednerb in #48: Hey @chibikun \r\nSorry for the late response...\r\n\r\nThis week I will work on this and release version 2.0.\r\n\r\nI'm looking forward to having support for the Japanese language :+1: "}],"action":{"name":"View Pull Request","url":"https://github.com/Lednerb/bilberry-hugo-theme/pull/48#issuecomment-361265046"}}}

**Comment by chibikun** [comment]
Hi Sascha,

ebenso sorry für die späte Antwort. Ich übersende Dir hier einfach das yaml für japanisch und DU kannst es dann ja ins repo packen wenn das ok ist.

Liebe Grüße,

David

**Comment by chibikun** [comment]
Hi Sascha,
I sent the japanese translations via mail. Was that ok?
David

**Comment by Lednerb** [comment]
Hi David, @chibikun 

thank you for your contribution, but I didn't receive your mail.

Can you please upload the file into a response message in this thread?

**Comment by chibikun** [comment]
Hi Sascha,

yaml was not accepted, so I just made it a txt file.

Cheers,
David
[jp.txt](https://github.com/Lednerb/bilberry-hugo-theme/files/1772915/jp.txt)

**Comment by Lednerb** [comment]
Hi @chibikun ,
I'm back and I'm working on this theme again.
One translation key is missing, would you please provide the translation for "Other languages" / "Andere Sprachen" ?

**Comment by chibikun** [comment]
Hi @Lednerb ,
sorry, was offline for a while but am happy to hear that you picked it up again. I am eagerly waiting for the functionality.
The translation for Other Languages is 
他言語

Cheers,
David

**Comment by Lednerb** [comment]
Merged into `development` branch.

**Pull request closed without merging**
