### PR TITLE
Turn bilberry theme into a hugo module

### PR DESCRIPTION
**Pull request by deining**
This PR turns the theme into a hugo module.
With `git`and `go` installed, making use of the bilberry theme is now as easy as:

```
hugo new site my_site
cd mysite
echo 'theme = "github.com/Lednerb/bilberry-hugo-theme"' >> config.toml
hugo server
```

Copying/cloning the theme in the themes folder is still possible of course.

If desired, I can extend the `Quickstart` section in `README.md`, explaining how to make use of the theme as module.

### CODE REVIEW

**Comment by igor-baiborodine** [comment]
@deining, yes, please update the Quickstart section in README.md.

**Comment by igor-baiborodine** [comment]
@deining, when using Go modules, if I need to customize my website,  can I use the same approach as with cloning the Bilberry theme into the themes folder. For example, I decide to switch to Go modules for my website [kiroule.com](https://github.com/igor-baiborodine/kiroule.com). Will the custom things from the  [layouts](https://github.com/igor-baiborodine/kiroule.com/tree/master/layouts) be merged with the Bilberry theme provided via the Go module?

**Comment by deining** [comment]
> @deining, when using Go modules, if I need to customize my website, can I use the same approach as with cloning the Bilberry theme into the themes folder.

Yes, you can.

> For example, I decide to switch to Go modules for my website [kiroule.com](https://github.com/igor-baiborodine/kiroule.com). Will the custom things from the [layouts](https://github.com/igor-baiborodine/kiroule.com/tree/master/layouts) folder be merged with the Bilberry theme provided via the Go module?

Yes, they will.

I would proposed the following procedure:
* you create a branch `module`in this repo
* I change my PR so that it targets newly created `module` branch
* you merge my commit into `module` branch
* you change your website `kiroule.com` so that it uses bilberry theme as module (this should be straightforward, I can assist you if needed)
* based on your experience, you decide whether to merge branch `module` into `main` (or not).

In my humble opionion, the module approach is superior to the traditional theme approach. A recent [blog post](https://chrisshort.net/from-git-submodule-to-hugo-modules-using-netlify/) about conversion from git submodule to hugo modules can serve as additional reference.

Please note that official hugo docs dropped section on [Installing and using themes](https://gohugobrasil.netlify.app/themes/installing-and-using-themes/) in favour of a section on  [Hugo modules](https://gohugo.io/hugo-modules/). So they think that Hugo modules are the future way to use themes, too.

**Comment by igor-baiborodine** [comment]
@deining, perfect, I will test the migration to Go modules with the [Bilberry Sandbox](https://github.com/igor-baiborodine/bilberry-hugo-theme-sandbox).

**Review by igor-baiborodine — CHANGES_REQUESTED** [review]
It does not work, and I cannot create and publish a working website based on modulized Bilberry theme.

**Comment by deining** [comment]
I brought #327 into a workable state. Since #327 contains commit 1c248abe9 (which is the only commit of this PR), I will close this as duplicate.

**Pull request closed without merging**
