### PR TITLE
Update to Font Awesome 5.12.0

### PR DESCRIPTION
**Pull request by setu4993**
Changes:
- Updates the version of Font Awesome to the latest.

Checked the icons that I am using and they show up correctly. Haven't verified if *all* icons show correctly. There were name changes going from [v4 to v5](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#name-changes).

### CODE REVIEW

**Comment by setu4993** [comment]
@Lednerb : This is ready for review.

**Comment by Lednerb** [comment]
Thank you for your contribution! :+1:

However, this will not be merged directly.

Official release is planned for version 2.0 of this theme.

Done by 0197b17

**Comment by setu4993** [comment]
@Lednerb: How can I contribute this to the v2 branch, then?

**Comment by Lednerb** [comment]
@setu4993 it's already within the latest `master` branch.

**Comment by setu4993** [comment]
Just saw the changes in `master`, thanks!

**Pull request closed without merging**
