### PR TITLE
Add Coral, Remark42

### PR DESCRIPTION
**Pull request by mzch**
Add Coral Remark42 comment engines. No needs?

### CODE REVIEW

**Comment by igor-baiborodine** [comment]
@Lednerb, I propose the following policy to accept or reject the integration of new commenting engines in the Bilberry theme. To be accepted, the commenting engine must meet the following two criteria:
1. The engine should be offered as a SAAS, i.e., you only need to create an account and configure the necessary settings on the engine's website.
2. If the engine is offered as a SAAS, it must have a free tier plan, e.g., Disqus.

The [Coral](https://coralproject.net/) and [Remark42](https://remark42.com/) commenting engines do not satisfy the criteria mentioned above.

Let me know what you think.

**Comment by Lednerb** [comment]
@igor-baiborodine thank you very much for your efforts! As always it's a pleasure to see what you do with this project!

I fully agree with your proposal.
Otherwise it would not be possible to maintain and test the theme. 
You've done a great job with the bilberry sandbox. 

SAAS engines with a free plan can be integrated, payed ones or self-hosted ones are more complicated.
In the past I've done this with the commento.io engine but also had to self-host the service (Btw it's no longer available).

I would also append another rule for third party services:

1. The engine should be offered as a SAAS, i.e., you only need to create an account and configure the necessary settings on the engine's website.
2. If the engine is offered as a SAAS, it must have a free tier plan, e.g., Disqus.
3. All the configuration steps needed to integrate a third-party service must take place in the `confg.toml` file and not within additional configuration in the `partial` files or any other.


The bilberry theme is a high quality one and I've called it Premium Theme in the past for that reason that it should be easy to use, well documented and tested as much as reasonable to work out of the box by doing all the configuration within the only file that must be configured anyway.

If you agree, we should add the rules to the `README.md` directly so anyone can check beforehand.

----

@mzch Thanks for your contribution!
Altough we are not going to merge this PR directly into the theme, it would be nice to have the code of the `partial` files linked in the discussion section, so other users can find it and profit from @mzch work. (@igor-baiborodine maybe via link to this PR?)

**Comment by igor-baiborodine** [comment]
@mzch, I'm closing this PR, but to add visibility to it, I created a new [discussion](https://github.com/Lednerb/bilberry-hugo-theme/discussions/442).

**Comment by mzch** [comment]
OK, thanks @igor-baiborodine !

**Pull request closed without merging**
